all: blocking02 newBlocking blocking 

blocking02:
	gcc blocking02.c -o blocking02
	# ./blocking02

newBlocking:
	gcc newBlocking.c -o newBlocking
	./newBlocking

blocking:
	gcc blocking.c -o blocking
	# ./blocking

clean:
	 rm blocking02 newBlocking blocking 

