all: no_blocking no_blockingCase02 

no_blocking:
	gcc no_blocking.c -o no_blocking
	./no_blocking

no_blockingCase02:
	gcc no_blockingCase02.c -o no_blockingCase02
	./no_blockingCase02

clean:
	 rm no_blocking no_blockingCase02 

